"""Generate the explicit offline Beta APIs patch script in the plugin data folder."""

from __future__ import annotations

from pathlib import Path


PATCH_SCRIPT_NAME = "enable_beta.py"


def render_patch_script(level_dat: Path, world_name: str, *, backup_keep: int = 5) -> str:
    level_dat = Path(level_dat).resolve()
    world_name = str(world_name)
    backup_keep = max(1, min(20, int(backup_keep)))

    return f'''# Auto-generated by endstone-bot.
# IMPORTANT: stop BDS completely before running this file.
#
# Windows:
#   python .\\plugins\\bot\\{PATCH_SCRIPT_NAME}
#
# Linux:
#   python plugins/bot/{PATCH_SCRIPT_NAME}

from pathlib import Path

from endstone_bot.level_dat import enable_beta_apis_safely


LEVEL_DAT = Path({str(level_dat)!r})
WORLD_NAME = {world_name!r}
BACKUP_ROOT = Path(__file__).resolve().parent / "level_dat_backups"
BACKUP_KEEP = {backup_keep}


def main() -> int:
    print("EndstoneBot Beta APIs patch")
    print(f"target: {{LEVEL_DAT}}")
    print("WARNING: BDS must be fully stopped before running this script.")

    result = enable_beta_apis_safely(
        LEVEL_DAT,
        backup_root=BACKUP_ROOT,
        world_name=WORLD_NAME,
        backup_keep=BACKUP_KEEP,
    )

    print(result.message)
    if result.backup_path:
        print(f"backup: {{result.backup_path}}")
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def write_patch_script(data_folder: Path, world_dir: Path, *, backup_keep: int = 5) -> Path:
    data_folder = Path(data_folder)
    world_dir = Path(world_dir).resolve()
    level_dat = world_dir / "level.dat"
    script_path = data_folder / PATCH_SCRIPT_NAME

    data_folder.mkdir(parents=True, exist_ok=True)
    content = render_patch_script(level_dat, world_dir.name, backup_keep=backup_keep)
    tmp = script_path.with_suffix(".py.tmp")
    tmp.write_text(content, encoding="utf-8", newline="\n")
    tmp.replace(script_path)
    return script_path
