# Auto-generated by endstone-bot.
# IMPORTANT: stop BDS completely before running this file.
#
# Windows:
#   python .\plugins\bot\enable_beta.py
#
# Linux:
#   python plugins/bot/enable_beta.py
#
# This file is intentionally self-contained and uses only Python's standard
# library. It does not import endstone_bot and does not require the plugin wheel
# to be importable by this interpreter.

from __future__ import annotations

import copy
import hashlib
import os
import stat
import struct
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


LEVEL_DAT = Path(__LEVEL_DAT_LITERAL__)
WORLD_NAME = __WORLD_NAME_LITERAL__
BACKUP_ROOT = Path(__file__).resolve().parent / "level_dat_backups"
BACKUP_KEEP = __BACKUP_KEEP_LITERAL__

TAG_END = 0
TAG_BYTE = 1
TAG_SHORT = 2
TAG_INT = 3
TAG_LONG = 4
TAG_FLOAT = 5
TAG_DOUBLE = 6
TAG_BYTE_ARRAY = 7
TAG_STRING = 8
TAG_LIST = 9
TAG_COMPOUND = 10
TAG_INT_ARRAY = 11
TAG_LONG_ARRAY = 12

MAX_NBT_DEPTH = 256
MAX_COLLECTION_LENGTH = 1_000_000
MAX_LEVEL_DAT_BYTES = 32 * 1024 * 1024

EXPERIMENTS_FIELDS: dict[str, int] = {
    "gametest": 1,
    "experiments_ever_used": 1,
    "saved_with_toggled_experiments": 1,
}


@dataclass(frozen=True)
class FieldInfo:
    tag_type: int
    payload_offset: int


@dataclass(frozen=True)
class PatchResult:
    status: str
    changed: bool
    message: str
    backup_path: Path | None = None

    @property
    def ok(self) -> bool:
        return self.status in {"already-enabled", "patched"}


class NBTReader:
    def __init__(self, data: bytes, offset: int = 0, depth: int = 0) -> None:
        self.data = data
        self.pos = offset
        self.depth = depth

    def read(self, size: int) -> bytes:
        if size < 0 or self.pos + size > len(self.data):
            raise EOFError("NBT data ended unexpectedly")
        value = self.data[self.pos:self.pos + size]
        self.pos += size
        return value

    def u8(self) -> int:
        return struct.unpack("<B", self.read(1))[0]

    def i8(self) -> int:
        return struct.unpack("<b", self.read(1))[0]

    def u16(self) -> int:
        return struct.unpack("<H", self.read(2))[0]

    def i16(self) -> int:
        return struct.unpack("<h", self.read(2))[0]

    def i32(self) -> int:
        return struct.unpack("<i", self.read(4))[0]

    def i64(self) -> int:
        return struct.unpack("<q", self.read(8))[0]

    def f32(self) -> float:
        return struct.unpack("<f", self.read(4))[0]

    def f64(self) -> float:
        return struct.unpack("<d", self.read(8))[0]

    def string(self) -> str:
        length = self.u16()
        return self.read(length).decode("utf-8")

    def _enter(self) -> None:
        self.depth += 1
        if self.depth > MAX_NBT_DEPTH:
            raise ValueError(f"NBT depth exceeded: {self.depth}")

    def _leave(self) -> None:
        self.depth -= 1

    @staticmethod
    def _check_count(count: int, kind: str) -> None:
        if count < 0 or count > MAX_COLLECTION_LENGTH:
            raise ValueError(f"Invalid NBT {kind} length: {count}")

    def skip_payload(self, tag_type: int) -> None:
        if tag_type == TAG_BYTE:
            self.read(1)
        elif tag_type == TAG_SHORT:
            self.read(2)
        elif tag_type in (TAG_INT, TAG_FLOAT):
            self.read(4)
        elif tag_type in (TAG_LONG, TAG_DOUBLE):
            self.read(8)
        elif tag_type == TAG_BYTE_ARRAY:
            count = self.i32()
            self._check_count(count, "byte array")
            self.read(count)
        elif tag_type == TAG_STRING:
            self.read(self.u16())
        elif tag_type == TAG_LIST:
            element_type = self.u8()
            count = self.i32()
            self._check_count(count, "list")
            if count and element_type == TAG_END:
                raise ValueError("Non-empty NBT list cannot use TAG_END")
            self._enter()
            try:
                for _ in range(count):
                    self.skip_payload(element_type)
            finally:
                self._leave()
        elif tag_type == TAG_COMPOUND:
            self._enter()
            try:
                while True:
                    child_type = self.u8()
                    if child_type == TAG_END:
                        break
                    self.string()
                    self.skip_payload(child_type)
            finally:
                self._leave()
        elif tag_type == TAG_INT_ARRAY:
            count = self.i32()
            self._check_count(count, "int array")
            self.read(count * 4)
        elif tag_type == TAG_LONG_ARRAY:
            count = self.i32()
            self._check_count(count, "long array")
            self.read(count * 8)
        else:
            raise ValueError(f"Unknown NBT tag type: {tag_type}")

    def payload(self, tag_type: int) -> Any:
        if tag_type == TAG_BYTE:
            return self.i8()
        if tag_type == TAG_SHORT:
            return self.i16()
        if tag_type == TAG_INT:
            return self.i32()
        if tag_type == TAG_LONG:
            return self.i64()
        if tag_type == TAG_FLOAT:
            return self.f32()
        if tag_type == TAG_DOUBLE:
            return self.f64()
        if tag_type == TAG_BYTE_ARRAY:
            count = self.i32()
            self._check_count(count, "byte array")
            return list(struct.unpack(f"<{count}b", self.read(count))) if count else []
        if tag_type == TAG_STRING:
            return self.string()
        if tag_type == TAG_LIST:
            element_type = self.u8()
            count = self.i32()
            self._check_count(count, "list")
            if count and element_type == TAG_END:
                raise ValueError("Non-empty NBT list cannot use TAG_END")
            self._enter()
            try:
                return [self.payload(element_type) for _ in range(count)]
            finally:
                self._leave()
        if tag_type == TAG_COMPOUND:
            self._enter()
            try:
                return self.compound()
            finally:
                self._leave()
        if tag_type == TAG_INT_ARRAY:
            count = self.i32()
            self._check_count(count, "int array")
            return list(struct.unpack(f"<{count}i", self.read(count * 4))) if count else []
        if tag_type == TAG_LONG_ARRAY:
            count = self.i32()
            self._check_count(count, "long array")
            return list(struct.unpack(f"<{count}q", self.read(count * 8))) if count else []
        raise ValueError(f"Unknown NBT tag type: {tag_type}")

    def compound(self) -> dict[str, Any]:
        result: dict[str, Any] = {}
        while True:
            tag_type = self.u8()
            if tag_type == TAG_END:
                return result
            name = self.string()
            if name in result:
                raise ValueError(f"Duplicate NBT compound field: {name}")
            result[name] = self.payload(tag_type)

    def root(self) -> dict[str, Any]:
        if self.u8() != TAG_COMPOUND:
            raise ValueError("level.dat root tag is not a Compound")
        self.string()
        return self.compound()


def parse_level_dat_header(data: bytes) -> tuple[int, int]:
    if len(data) < 9:
        raise ValueError("level.dat is too short")
    version, declared_length = struct.unpack("<II", data[:8])
    actual_length = len(data) - 8
    if declared_length != actual_length:
        raise ValueError(
            f"level.dat NBT length mismatch: declared={declared_length}, actual={actual_length}"
        )
    return version, declared_length


def read_bedrock_nbt(data: bytes, *, has_header: bool = False, strict: bool = True) -> dict[str, Any]:
    offset = 0
    if has_header:
        parse_level_dat_header(data)
        offset = 8
    reader = NBTReader(data, offset)
    value = reader.root()
    if strict and reader.pos != len(data):
        raise ValueError(f"Trailing bytes after NBT root: {len(data) - reader.pos}")
    return value


def get_root_body_offset(data: bytes, *, has_header: bool = False) -> int:
    offset = 8 if has_header else 0
    if has_header:
        parse_level_dat_header(data)
    reader = NBTReader(data, offset)
    if reader.u8() != TAG_COMPOUND:
        raise ValueError("Root tag is not a Compound")
    reader.string()
    return reader.pos


def scan_compound_fields(data: bytes, compound_body_offset: int) -> tuple[dict[str, FieldInfo], int]:
    reader = NBTReader(data, compound_body_offset)
    fields: dict[str, FieldInfo] = {}
    while True:
        tag_offset = reader.pos
        tag_type = reader.u8()
        if tag_type == TAG_END:
            return fields, tag_offset
        name = reader.string()
        if name in fields:
            raise ValueError(f"Duplicate NBT compound field: {name}")
        fields[name] = FieldInfo(tag_type=tag_type, payload_offset=reader.pos)
        reader.skip_payload(tag_type)


def make_byte_tag_bytes(name: str, value: int) -> bytes:
    encoded = name.encode("utf-8")
    if len(encoded) > 0xFFFF:
        raise ValueError("NBT tag name is too long")
    return (
        struct.pack("<B", TAG_BYTE)
        + struct.pack("<H", len(encoded))
        + encoded
        + struct.pack("<b", int(value))
    )


def make_compound_tag_bytes(name: str, body: bytes) -> bytes:
    encoded = name.encode("utf-8")
    if len(encoded) > 0xFFFF:
        raise ValueError("NBT tag name is too long")
    return (
        struct.pack("<B", TAG_COMPOUND)
        + struct.pack("<H", len(encoded))
        + encoded
        + body
        + struct.pack("<B", TAG_END)
    )


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _validate_level_dat_bytes(raw: bytes) -> dict[str, Any]:
    if len(raw) > MAX_LEVEL_DAT_BYTES:
        raise ValueError(f"level.dat is too large: {len(raw)} bytes")
    parse_level_dat_header(raw)
    return read_bedrock_nbt(raw, has_header=True, strict=True)


def _build_patch(raw: bytes) -> bytes | None:
    before = _validate_level_dat_bytes(raw)
    root_body = get_root_body_offset(raw, has_header=True)
    root_fields, root_end = scan_compound_fields(raw, root_body)

    patches: list[tuple[int, int, bytes]] = []
    experiments_info = root_fields.get("experiments")

    if experiments_info is None:
        body = b"".join(make_byte_tag_bytes(name, value) for name, value in EXPERIMENTS_FIELDS.items())
        patches.append((root_end, 0, make_compound_tag_bytes("experiments", body)))
    else:
        if experiments_info.tag_type != TAG_COMPOUND:
            raise ValueError("experiments exists but is not a Compound")

        exp_fields, exp_end = scan_compound_fields(raw, experiments_info.payload_offset)
        for name, wanted in EXPERIMENTS_FIELDS.items():
            info = exp_fields.get(name)
            if info is None:
                patches.append((exp_end, 0, make_byte_tag_bytes(name, wanted)))
                continue
            if info.tag_type != TAG_BYTE:
                raise ValueError(f"experiments.{name} exists but is not a Byte")
            current = struct.unpack("<b", raw[info.payload_offset:info.payload_offset + 1])[0]
            if current != wanted:
                patches.append((info.payload_offset, 1, struct.pack("<b", wanted)))

    if not patches:
        experiments = before.get("experiments")
        if (
            isinstance(experiments, dict)
            and all(experiments.get(name) == value for name, value in EXPERIMENTS_FIELDS.items())
        ):
            return None
        raise ValueError("Beta APIs state is inconsistent")

    result = bytearray(raw)
    for offset, delete_len, insert_bytes in sorted(patches, key=lambda item: item[0], reverse=True):
        result[offset:offset + delete_len] = insert_bytes

    struct.pack_into("<I", result, 4, len(result) - 8)
    candidate = bytes(result)
    after = _validate_level_dat_bytes(candidate)

    expected = copy.deepcopy(before)
    experiments = expected.get("experiments")
    if experiments is None:
        experiments = {}
        expected["experiments"] = experiments
    if not isinstance(experiments, dict):
        raise ValueError("experiments semantic structure is invalid")
    experiments.update(EXPERIMENTS_FIELDS)

    if after != expected:
        raise ValueError("NBT semantic changes exceeded the allowed experiment fields")

    return candidate


def is_beta_apis_enabled(level_dat_path: Path) -> bool:
    try:
        raw = level_dat_path.read_bytes()
        data = _validate_level_dat_bytes(raw)
        experiments = data.get("experiments", {})
        return (
            isinstance(experiments, dict)
            and all(experiments.get(name) == value for name, value in EXPERIMENTS_FIELDS.items())
        )
    except Exception:
        return False


def _fsync_dir(path: Path) -> None:
    if os.name == "nt":
        return
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _atomic_write(path: Path, data: bytes, mode: int) -> None:
    tmp = path.with_name(path.name + ".endstone-bot.tmp")
    try:
        with open(tmp, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.chmod(tmp, stat.S_IMODE(mode))
        except OSError:
            pass
        os.replace(tmp, path)
        _fsync_dir(path.parent)
    finally:
        try:
            tmp.unlink(missing_ok=True)
        except Exception:
            pass


def _create_verified_backup(
    original: bytes,
    backup_root: Path,
    world_name: str,
    mode: int,
) -> Path:
    safe_world = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in world_name) or "world"
    target_dir = backup_root / safe_world
    target_dir.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    digest = _sha256(original)
    backup = target_dir / f"level.dat.{stamp}.{digest[:12]}.bak"
    counter = 1
    while backup.exists():
        backup = target_dir / f"level.dat.{stamp}.{digest[:12]}.{counter}.bak"
        counter += 1

    tmp = backup.with_suffix(backup.suffix + ".tmp")
    try:
        with open(tmp, "wb") as handle:
            handle.write(original)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.chmod(tmp, stat.S_IMODE(mode))
        except OSError:
            pass
        os.replace(tmp, backup)
        _fsync_dir(target_dir)
    finally:
        try:
            tmp.unlink(missing_ok=True)
        except Exception:
            pass

    if _sha256(backup.read_bytes()) != digest:
        backup.unlink(missing_ok=True)
        raise IOError("level.dat backup verification failed")
    return backup


def _prune_backups(backup_root: Path, world_name: str, keep: int) -> None:
    try:
        keep = max(1, min(20, int(keep)))
        safe_world = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in world_name) or "world"
        folder = backup_root / safe_world
        if not folder.is_dir():
            return
        backups = sorted(
            folder.glob("level.dat.*.bak"),
            key=lambda p: p.stat().st_mtime_ns,
            reverse=True,
        )
    except (OSError, ValueError, TypeError):
        return

    for old in backups[keep:]:
        try:
            old.unlink()
        except OSError:
            pass


def enable_beta_apis_safely(
    level_dat_path: Path,
    *,
    backup_root: Path,
    world_name: str,
    backup_keep: int = 5,
) -> PatchResult:
    try:
        if level_dat_path.is_symlink():
            return PatchResult("rejected", False, "level.dat is a symlink; refusing to modify it")

        st = level_dat_path.stat()
        if not stat.S_ISREG(st.st_mode):
            return PatchResult("rejected", False, "level.dat is not a regular file")

        original = level_dat_path.read_bytes()
        original_hash = _sha256(original)
        candidate = _build_patch(original)
        if candidate is None:
            return PatchResult("already-enabled", False, "Beta APIs already enabled")

        current = level_dat_path.read_bytes()
        if _sha256(current) != original_hash:
            return PatchResult("rejected", False, "level.dat changed during validation; refusing to write")

        backup = _create_verified_backup(
            original,
            backup_root,
            world_name,
            st.st_mode,
        )

        try:
            _atomic_write(level_dat_path, candidate, st.st_mode)
            written = level_dat_path.read_bytes()
            if _sha256(written) != _sha256(candidate):
                raise IOError("SHA-256 mismatch after atomic replacement")
            if not is_beta_apis_enabled(level_dat_path):
                raise IOError("Beta APIs verification failed after replacement")
        except Exception as write_error:
            rollback_error: Exception | None = None
            try:
                _atomic_write(level_dat_path, original, st.st_mode)
                if _sha256(level_dat_path.read_bytes()) != original_hash:
                    raise IOError("rollback SHA-256 does not match the original")
            except Exception as exc:
                rollback_error = exc

            if rollback_error is not None:
                return PatchResult(
                    "rollback-failed",
                    False,
                    f"write failed and rollback failed: write={write_error}; rollback={rollback_error}; backup={backup}",
                    backup,
                )
            return PatchResult(
                "rolled-back",
                False,
                f"post-write verification failed; original restored: {write_error}",
                backup,
            )

        _prune_backups(backup_root, world_name, backup_keep)
        return PatchResult("patched", True, "Beta APIs enabled successfully", backup)

    except FileNotFoundError:
        return PatchResult("rejected", False, f"level.dat not found: {level_dat_path}")
    except Exception as exc:
        return PatchResult("rejected", False, f"safety validation failed; level.dat was not modified: {exc}")


def main() -> int:
    print("EndstoneBot Beta APIs patch")
    print(f"target: {LEVEL_DAT}")
    print("WARNING: BDS must be fully stopped before running this script.")

    result = enable_beta_apis_safely(
        LEVEL_DAT,
        backup_root=BACKUP_ROOT,
        world_name=WORLD_NAME,
        backup_keep=BACKUP_KEEP,
    )

    print(result.message)
    if result.backup_path:
        print(f"backup: {result.backup_path}")
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
